version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run: docker build -t ghcr.io/sathis1205-mt/parking-back-end:latest .
      - run: echo $GITHUB_TOKEN | docker login ghcr.io -u $GITHUB_USERNAME --password-stdin
      - run: docker push ghcr.io/sathis1205-mt/parking-back-end:latest:latest

workflows:
  version: 2
  build:
    jobs:
      - build
